### ISSUE TITLE
Dados dos livros

### ISSUE THREAD

**Issue by adelsonsljunior** [adelsonsljunior/pmov-bookstore-api#3]
Depois de escolher os atributos dos livros, na [issue 1](https://github.com/adelsonsljunior/pmov-bookstore-api/issues/1). Colocar aqui os dados de cada livro pra fazer a seed da database. 🤙

**Comment by Felipkw** [comment]
[
  {
    "Livro 1": {
      "Título": "O Hobbit",
      "Autor": "J.R.R. Tolkien",
      "Ano de publicação": 2019,
      "Descrição": "Bilbo Bolseiro era um dos mais respeitáveis hobbits de todo o Condado até que, um dia, o mago Gandalf bate à sua porta. A partir de então, toda sua vida pacata e campestre soprando anéis de fumaça com seu belo cachimbo começa a mudar. Ele é convocado a participar de uma aventura por ninguém menos do que Thorin Escudo-de-Carvalho, um príncipe do poderoso povo dos Anãos. Esta jornada fará Bilbo, Gandalf e 13 anãos atravessarem a Terra-média, passando por inúmeros perigos, como os imensos trols, as Montanhas Nevoentas infestadas de gobelins ou a muito antiga e misteriosa Trevamata, até chegarem (se conseguirem) na Montanha Solitária. Lá está um incalculável tesouro, mas há um porém. Deitado em cima dele está Smaug, o Dourado, um dragão malicioso que... bem, você terá que ler para descobrir.",
      "Número de páginas": 385,
      "Url": "https://m.media-amazon.com/images/I/511+-lOOtsL._SY445_SX342_.jpg",
      "Valor": 30.00
    }
  },
  {
    "Livro 2": {
      "Título": "A volta ao mundo em 80 dias",
      "Autor": "Júlio Verne",
      "Ano de publicação": 2019,
      "Descrição": "Phileas Fogg, um inglês rico, metódico e um tanto quanto solitário aposta com seus colegas do clube de jogos que conseguirá dar uma volta ao mundo em apenas 80 dias. Para tal feito, o excêntrico Fogg convida seu fiel empregado Jean Passepartout e juntos viverão muitas aventuras.",
      "Número de páginas": 304,
      "Url": "https://m.media-amazon.com/images/I/71UKvlLXALL._AC_UY218_.jpg",
      "Valor": 40.00
    }
  },
  {
    "Livro 3": {
      "Título": "A cinco passos de você",
      "Autor": "Rachael Lippincott",
      "Ano de publicação": 2019,
      "Descrição": "Stella Grant gosta de estar no controle. Ela parece ser uma adolescente típica, mas em sua rotina há listas de tarefas e inúmeros remédios que ela deve tomar para controlar a fibrose cística, uma doença crônica que impede que seus pulmões funcionem como deveriam. Suas prioridades são manter seus pais felizes e conseguir um transplante – e uma coisa não existe sem a outra. Mas para ganhar pulmões novos, Stella precisa seguir seu tratamento à risca e eliminar qualquer chance de infecção, o que significa que ela não pode ficar a menos que dois metros de distância – ou seis passos – de outros pacientes com a doença. O primeiro item é fácil para ela, mas o segundo pode se provar mais difícil do que ela esperava. O único controle que Will Newman deseja é o de sua própria vida. Ele não dá a mínima para o novo tratamento experimental para o qual foi selecionado e não aguenta mais a pressão de sua mãe para que melhore. Prestes a completar dezoito anos, ele mal pode esperar para finalmente se livrar das máquinas e hospitais, usando o pouco de vida que ainda lhe resta para conhecer o mundo. Stella e Will são muito diferentes. Ao mesmo tempo, a doença que os une não é a única coisa que têm em comum. Eles têm que ficar a cinco passos um do outro, mas, conforme a conexão entre os dois aumenta, a vontade de burlar a distância física parece insuportável. Um grande amor vale um passo roubado?",
      "Número de páginas": 288,
      "Url": "https://m.media-amazon.com/images/I/81Q11TuUR3L._AC_UY218_.jpg",
      "Valor": 45.00
    }
  },
  {
    "Livro 4": {
      "Título": "Dom Casmurro",
      "Autor": "Machado de Assis",
      "Ano de publicação": 2019,
      "Descrição": "Em Dom Casmurro, o narrador Bento Santiago retoma a infância que passou na Rua de Matacavalos e conta a história do amor e das desventuras que viveu com Capitu, uma das personagens mais enigmáticas e intrigantes da literatura brasileira. Nas páginas deste romance, encontra-se a versão de um homem perturbado pelo ciúme, que revela aos poucos sua psicologia complexa e enreda o leitor em sua narrativa ambígua acerca do acontecimento ou não do adultério da mulher com olhos de ressaca, uma das maiores polêmicas da literatura brasileira.",
      "Número de páginas": 208,
      "Url": "https://m.media-amazon.com/images/I/61x1ZHomWUL._AC_UY218_.jpg",
      "Valor": 20.00
    }
  },
  {
    "Livro 5": {
      "Título": "Sherlock Holmes - O cão dos Baskerville",
      "Autor": "Arthur Conan Doyle",
      "Ano de publicação": 2019,
      "Descrição": "Holmes investiga a morte do milionário Sir Charles Baskerville que foi encontrado em um pântano próximo a sua casa. Uma lenda local dizia que ele foi assassinado por um cão que assombrava a região. Será isso mesmo?",
      "Número de páginas": 224,
      "Url": "https://m.media-amazon.com/images/I/61oliHz5jSL._AC_UY218_.jpg",
      "Valor": 30.00
    }
  },
  {
    "Livro 6": {
      "Título": "Para todos os garotos que já amei",
      "Autor": "Jenny Han",
      "Ano de publicação": 2015,
      "Descrição": "Lara Jean guarda suas cartas de amor em uma caixa azul-petróleo que ganhou da mãe. Não são cartas que ela recebeu de alguém, mas que ela mesma escreveu. Uma para cada garoto que amou — cinco ao todo. São cartas sinceras, sem joguinhos nem fingimentos, repletas de coisas que Lara Jean não diria a ninguém, confissões de seus sentimentos mais profundos. Até que um dia essas cartas secretas são misteriosamente enviadas aos destinatários, e de uma hora para outra a vida amorosa de Lara Jean sai do papel e se transforma em algo que ela não pode mais controlar.",
      "Número de páginas": 320,
      "Url": "https://m.media-amazon.com/images/I/71vGDXuc7uS._SY425_.jpg",
      "Valor": 25.00
    }
  },
  {
    "Livro 7": {
      "Título": "O sol é para todos",
      "Autor": "Harper Lee",
      "Ano de publicação": 2006,
      "Descrição": "Um dos maiores clássicos da literatura mundial. O sol é para todos ganhou o Prêmio Pulitzer em 1961 e deu origem a um filme homônimo, vencedor do Oscar de melhor roteiro adaptado, em 1962. Lançado pela primeira vez em 1960, até hoje vende mais de um milhão de cópias por ano em língua inglesa. Uma história atemporal sobre tolerância, perda da inocência e conceito de justiça.",
      "Número de páginas": 349,
      "Url": "https://m.media-amazon.com/images/I/91WKPd60P4L._SY425_.jpg",
      "Valor": 15.00
    }
  },
  {
    "Livro 8": {
      "Título": "O Ceifador",
      "Autor": "Neal Shusterman",
      "Ano de publicação": 2017,
      "Descrição": "A humanidade venceu todas as barreiras: fome, doenças, guerras, miséria… Até mesmo a morte. Agora os ceifadores são os únicos que podem pôr fim a uma vida, impedindo que o crescimento populacional vá além do limite e a Terra deixe de comportar a população por toda a eternidade. Citra e Rowan são adolescentes escolhidos como aprendizes de ceifador - um papel que nenhum dos dois quer desempenhar. Para receberem o anel e o manto da Ceifa, os adolescentes precisam dominar a \"arte\" da coleta, ou seja, precisam aprender a matar. Porém, se falharem em sua missão - ou se a cumplicidade no treinamento se tornar algo mais -, podem colocar a própria vida em risco.",
      "Número de páginas": 448,
      "Url": "https://m.media-amazon.com/images/I/91LldWCllgS._AC_UY218_.jpg",
      "Valor": 40.00
    }
  },
  {
    "Livro 9": {
      "Título": "Fortaleza Digital",
      "Autor": "Dan Brown",
      "Ano de publicação": 2019,
      "Descrição": "Responsável por monitorar as comunicações de todo o planeta e proteger informações do governo dos Estados Unidos, a ultrassecreta NSA, a Agência de Segurança Nacional americana, investiu às escondidas numa arma revolucionária para combater a ação de grupos terroristas na era da informática. Seu trunfo é o supercomputador TRANSLTR, capaz de decifrar em poucos minutos qualquer mensagem encriptada enviada pela Internet. Quando o infalível TRANSLTR é paralisado por um misterioso código, a agência convoca a chefe do Departamento de Criptografia, a matemática Susan Fletcher, para investigar o que está acontecendo. Susan faz uma descoberta aterradora: a NSA se tornou refém do gênio da computação Ensei Tankado. Demitido da agência por discordar da sua política de respeito aos direitos civis, o programador exige que a NSA revele a existência do TRANSLTR à população. Caso contrário, ele divulgará na Internet a fórmula de seu código indecifrável, o Fortaleza Digital. Tankado morre misteriosamente antes de cumprir sua ameaça, dando início a uma corrida desesperada que se desenrola paralelamente nos corredores do submundo do poder, nos arranha-céus de Tóquio e nas ruas de Sevilha. Enquanto Susan usa seu talento como criptógrafa para tentar desvendar o enigma do Fortaleza Digital, seu namorado, o especialista em idiomas David Becker, sai em busca de um anel deixado por Tankado que pode conter a chave do código. Envolvidos numa trama maquiavélica, Susan e David precisam travar uma batalha de vida ou morte para evitar uma tragédia para a segurança nacional americana e impedir que o equilíbrio de forças no mundo mude para sempre.",
      "Número de páginas": 336,
      "Url": "https://m.media-amazon.com/images/I/81JZXzyZUIL._AC_UY218_.jpg",
      "Valor": 35.00
    }
  },
  {
    "Livro 10": {
      "Título": "A anatomia do estado",
      "Autor": "Murray Rothbard",
      "Ano de publicação": 2019,
      "Descrição": "O Estado é a “organização dos meios políticos”; é a sistematização do processo predatório sobre um determinado território. O Estado provê um canal legal, ordenado e sistemático para a predação da propriedade privada; ele garante provisão certa, segura e relativamente “pacífica” para a casta parasítica na sociedade. O Estado nunca foi criado por um “contrato social”; ele sempre nasceu da conquista e da exploração. Um método de nascimento de um Estado pode ser ilustrado como segue: nas montanhas da “Ruritânia” do Sul, um grupo de bandidos se organiza para obter o controle físico do território, e finalmente o chefe do grupo se auto-proclama “Rei do governo soberano e independente da Ruritânia do Sul”; e, se ele e seus homens tiverem a força para manter tal domínio por algum tempo, pasmem!, um novo Estado terá se unido à “família de nações”, e os que antes eram meros bandidos terão se transformado na nobreza legítima do reino.",
      "Número de páginas": 80,
      "Url": "https://m.media-amazon.com/images/I/71-wZmQh-WL._AC_UY218_.jpg",
      "Valor": 19.99
    }
  }
]
{
    "Livro 11": {
        "Título": "Razão e Sensibilidade",
        "Autor": "Jane Austen",
        "Ano de publicação": 2018,
        "Descrição": "Razão e Sensibilidade é um livro em que as irmãs Elinor e Marianne representam uma dualidade, de maneira alternada, ao longo da narrativa...",
        "Número de páginas": 400,
        "Url": "https://m.media-amazon.com/images/I/81Vv52MKZ5L._AC_UY218_.jpg",
        "Valor": 24.99
    },
    "Livro 12": {
        "Título": "Anne Frank",
        "Autor": "Anne Frank",
        "Ano de publicação": 2014,
        "Descrição": "O diário de Anne Frank, o depoimento da pequena Anne, morta pelos nazistas após passar anos escondida no sótão de uma casa em Amsterdã...",
        "Número de páginas": 416,
        "Url": "https://m.media-amazon.com/images/I/91tOJgXRfzL._AC_UY218_.jpg",
        "Valor": 10.00
    },
    "Livro 13": {
        "Título": "As Aventuras de Tintim: Rumo à Lua",
        "Autor": "Hergé",
        "Ano de publicação": 2007,
        "Descrição": "Ao regressar do país do Ouro Negro, o capitão Haddock fica sabendo que o professor Girassol partira havia três semanas com um estrangeiro desconhecido...",
        "Número de páginas": 64,
        "Url": "https://m.media-amazon.com/images/I/91E4TXOmtMS._AC_UY218_.jpg",
        "Valor": 8.00
    },
    "Livro 14": {
        "Título": "Moby Dick",
        "Autor": "Herman Melville",
        "Ano de publicação": 2020,
        "Descrição": "Publicada em 1851, Moby Dick é considerada a obra prima de Melville e narra a busca por vingança do Capitão Ahab pela baleia branca Moby Dick...",
        "Número de páginas": 72,
        "Url": "https://m.media-amazon.com/images/I/81HHJ7P2jVL._AC_UY218_.jpg",
        "Valor": 40.00
    },
    "Livro 15": {
        "Título": "Como fazer amigos e influenciar pessoas",
        "Autor": "Dale Carnegie",
        "Ano de publicação": 2019,
        "Descrição": "Um dos maiores clássicos de todos os tempos, Como fazer amigos e influenciar pessoas é considerado a Bíblia dos relacionamentos interpessoais...",
        "Número de páginas": 256,
        "Url": "https://m.media-amazon.com/images/I/71x-i7sKSvL._AC_UY218_.jpg",
        "Valor": 17.99
    },
    "Livro 16": {
        "Título": "Orgulho e Preconceito",
        "Autor": "Jane Austen",
        "Ano de publicação": 2018,
        "Descrição": "Orgulho e preconceito é o livro mais famoso de Jane Austen e possui uma série de personagens inesquecíveis e um enredo memorável...",
        "Número de páginas": 424,
        "Url": "https://m.media-amazon.com/images/I/81o1EY3JblL._AC_UY218_.jpg",
        "Valor": 45.00
    },
    "Livro 17": {
        "Título": "1984",
        "Autor": "George Orwell",
        "Ano de publicação": 2009,
        "Descrição": "Winston, herói de 1984, último romance de George Orwell, vive aprisionado na engrenagem totalitária de uma sociedade completamente dominada pelo Estado...",
        "Número de páginas": 416,
        "Url": "https://m.media-amazon.com/images/I/819js3EQwbL._AC_UY218_.jpg",
        "Valor": 19.99
    },
    "Livro 18": {
        "Título": "É assim que começa",
        "Autor": "Collen Hoover",
        "Ano de publicação": 2022,
        "Descrição": "Lily e o seu ex-marido, Ryle, acabaram de se adaptar numa situação de compartilhamento de guarda quando, de repente, ela se reencontra com seu primeiro amor, Atlas...",
        "Número de páginas": 336,
        "Url": "https://m.media-amazon.com/images/I/81Izv2GRWoL._AC_UY218_.jpg",
        "Valor": 39.99
    },
    "Livro 19": {
        "Título": "Caraval",
        "Autor": "Stephanie Garber",
        "Ano de publicação": 2022,
        "Descrição": "Os anos de espera acabaram: a jovem Scarlett Dragna finalmente recebeu o tão esperado convite para participar do Caraval...",
        "Número de páginas": 352,
        "Url": "https://m.media-amazon.com/images/I/81HB-DJUVHL._SY425_.jpg",
        "Valor": 40.00
    },
    "Livro 20": {
        "Título": "É assim que acaba",
        "Autor": "Collen Hoover",
        "Ano de publicação": 2018,
        "Descrição": "Em É assim que acaba, Colleen Hoover nos apresenta Lily, uma jovem que se mudou de uma cidadezinha do Maine para Boston...",
        "Número de páginas": 368,
        "Url": "https://m.media-amazon.com/images/I/91r5G8RxqfL._AC_UY218_.jpg",
        "Valor": 45.00
    }
}
{
    "Livro 21": {
        "Título": "Dois erros, um acerto",
        "Autor": "Chloe Liese",
        "Ano de publicação": 2023,
        "Descrição": "Quando Jamie Westenberg e Bea Wilmot se conhecem, fica claro que eles não poderiam ser mais diferentes...",
        "Número de páginas": 336,
        "Url": "https://m.media-amazon.com/images/I/81pLpCoHQVL._AC_UY218_.jpg",
        "Valor": 15.00
    },
    "Livro 22": {
        "Título": "O morro dos ventos uivantes",
        "Autor": "Emily Brontë",
        "Ano de publicação": 2022,
        "Descrição": "As brilhantes habilidades narrativas de Emily Brontë são apresentadas de maneira perturbadora nesta obra-prima da literatura universal...",
        "Número de páginas": 256,
        "Url": "https://m.media-amazon.com/images/I/91bW7gS9P2L._AC_UY218_.jpg",
        "Valor": 24.99
    },
    "Livro 23": {
        "Título": "A culpa é das estrelas",
        "Autor": "John Green",
        "Ano de publicação": 2014,
        "Descrição": "Hazel é uma paciente terminal. Ainda que, por um milagre da medicina, seu tumor tenha encolhido bastante...",
        "Número de páginas": 288,
        "Url": "https://m.media-amazon.com/images/I/51M9IbBqxCL._AC_UY218_.jpg",
        "Valor": 17.99
    },
    "Livro 24": {
        "Título": "Fourth Wing",
        "Autor": "Rebecca Yarros",
        "Ano de publicação": 2023,
        "Descrição": "Welcome to the brutal and elite world of Basgiath War College, where everyone has an agenda, and every night could be your last...",
        "Número de páginas": 512,
        "Url": "https://m.media-amazon.com/images/I/91N2N6HBQQL._AC_UY218_.jpg",
        "Valor": 38.99
    },
    "Livro 25": {
        "Título": "Coraline",
        "Autor": "Neil Gaiman",
        "Ano de publicação": 2020,
        "Descrição": "Certas portas não devem ser abertas. E Coraline descobre isso pouco tempo depois de chegar com os pais à sua nova casa...",
        "Número de páginas": 224,
        "Url": "https://m.media-amazon.com/images/I/91zkcDFU8-L._AC_UY218_.jpg",
        "Valor": 30.00
    },
    "Livro 26": {
        "Título": "Eu e Esse Meu Coração",
        "Autor": "C. C. Hunter",
        "Ano de publicação": 2018,
        "Descrição": "Leah MacKenzie, de 17 anos, não tem coração. O que a mantém viva é um coração artificial que ela carrega dentro de uma mochila...",
        "Número de páginas": 424,
        "Url": "https://m.media-amazon.com/images/I/613df-gsfIL._AC_UY218_.jpg",
        "Valor": 40.00
    },
    "Livro 27": {
        "Título": "Daisy Jones and The Six",
        "Autor": "Taylor Jenkins Reid",
        "Ano de publicação": 2019,
        "Descrição": "Embalado pelo melhor do rock’n’roll, um romance inesquecível sobre uma banda dos anos 1970, sua apaixonante vocalista e o amor à música...",
        "Número de páginas": 360,
        "Url": "https://www.amazon.com.br/Daisy-Jones-Six-hist%C3%B3ria-m%C3%BAsica/dp/8584391401/ref=sr_1_1?crid=1SDK78VK99DI9&keywords=daisy+jones+and+the+six&qid=1695325734&s=books&sprefix=daisy+%2Cstripbooks%2C154&sr=1-1",
        "Valor": 25.00
    },
    "Livro 28": {
        "Título": "A Biblioteca da Meia Noite",
        "Autor": "Matt Haig",
        "Ano de publicação": 2021,
        "Descrição": "Aos 35 anos, Nora Seed é uma mulher cheia de talentos e poucas conquistas. Arrependida das escolhas que fez no passado...",
        "Número de páginas": 308,
        "Url": "https://m.media-amazon.com/images/I/81iqH8dpjuL._AC_UY218_.jpg",
        "Valor": 20.00
    },
    "Livro 29": {
        "Título": "Estilhaça-me",
        "Autor": "Tahereh Mafi",
        "Ano de publicação": 2018,
        "Descrição": "Um toque é o bastante. Com apenas um toque, Juliette Ferrars é capaz de fazer um homem adulto se ajoelhar de dor e implorar por misericórdia...",
        "Número de páginas": 290,
        "Url": "https://m.media-amazon.com/images/I/71P-Mok4cqL._AC_UY218_.jpg",
        "Valor": 30.00
    },
    "Livro 30": {
        "Título": "As crônicas de Nárnia",
        "Autor": "C. S. Lewis",
        "Ano de publicação": 2009,
        "Descrição": "Viagens ao fim do mundo, criaturas fantásticas e batalhas épicas entre o bem e o mal - o que mais um leitor poderia querer de um livro?...",
        "Número de páginas": 752,
        "Url": "https://m.media-amazon.com/images/I/71yJLhQekBL._AC_UY218_.jpg",
        "Valor": 60.00
    }
}
{
    "Livro 31": {
        "Título": "Harry Potter e a Pedra Filosofal",
        "Autor": "J. K. Rowling",
        "Ano de publicação": 2017,
        "Descrição": "Harry Potter é um garoto cujos pais, feiticeiros, foram assassinados por um poderosíssimo bruxo quando ele ainda era um bebê. Ele foi levado, então, para a casa dos tios que nada tinham a ver com o sobrenatural...",
        "Número de páginas": 208,
        "Url": "https://m.media-amazon.com/images/I/41897yAI4LL._SY445_SX342_.jpg",
        "Valor": 20.00
    },
    "Livro 32": {
        "Título": "Cipreste Triste",
        "Autor": "Agatha Christie",
        "Ano de publicação": 2014,
        "Descrição": "A dona de uma mansão no interior da Inglaterra morre durante o sono, depois de padecer de uma longa doença. Enquanto a família ainda se recupera do golpe, uma jovem aparece morta nas redondezas...",
        "Número de páginas": 267,
        "Url": "https://m.media-amazon.com/images/I/81fTxVMM4XL._AC_UY218_.jpg",
        "Valor": 25.00
    },
    "Livro 33": {
        "Título": "A torre da Andorinha - The Witcher",
        "Autor": "Andrzej Sapkowski",
        "Ano de publicação": 2020,
        "Descrição": "O bruxo segue em direção ao sul, convencido de que Ciri vai se casar em breve com o imperador de Nilfgaard. Os assassinos impiedosos de Nilfgaard já estão seguindo os rastros de Ciri...",
        "Número de páginas": 450,
        "Url": "https://m.media-amazon.com/images/I/51JbQqNfsyS._SY425_.jpg",
        "Valor": 50.00
    },
    "Livro 34": {
        "Título": "Harry Potter e o Prisioneiro de Azkaban",
        "Autor": "J. K. Rowling",
        "Ano de publicação": 2017,
        "Descrição": "As aulas estão de volta à Hogwarts e Harry Potter não vê a hora de embarcar no expresso a vapor que o levará de volta à escola de bruxaria...",
        "Número de páginas": 288,
        "Url": "https://m.media-amazon.com/images/I/41kT95iZ81L._SY445_SX342_.jpg",
        "Valor": 24.99
    },
    "Livro 35": {
        "Título": "Hábitos Atômicos",
        "Autor": "James Clear",
        "Ano de publicação": 2019,
        "Descrição": "Pequenas mudanças, resultados impressionantes. Não importa quais sejam seus objetivos, Hábitos Atômicos oferece um método eficaz para você se aprimorar ― todos os dias...",
        "Número de páginas": 320,
        "Url": "https://m.media-amazon.com/images/I/81eT2pjx4jL._SY425_.jpg",
        "Valor": 15.00
    },
    "Livro 36": {
        "Título": "A Bíblia Sagrada",
        "Autor": "Thomas Nelson Brasil",
        "Ano de publicação": 2020,
        "Descrição": "Essa Bíblia ACF é para aqueles que preferem uma linguagem mais tradicional ao ler a Palavra. Nesta tradução mais formal...",
        "Número de páginas": 1600,
        "Url": "https://m.media-amazon.com/images/I/511up5B+poL._SY445_SX342_.jpg",
        "Valor": 40.00
    },
    "Livro 37": {
        "Título": "Corte de asas e ruína",
        "Autor": "Sarah J. Maas",
        "Ano de publicação": 2022,
        "Descrição": "Seguindo os acontecimentos do volume anterior, acompanhamos a saga de Feyre Archeon, que suportou a fome, o frio e a desesperança...",
        "Número de páginas": 686,
        "Url": "https://m.media-amazon.com/images/I/71yuikaNMhL._AC_UY218_.jpg",
        "Valor": 30.00
    },
    "Livro 38": {
        "Título": "Heartstopper",
        "Autor": "Alice Oseman",
        "Ano de publicação": 2021,
        "Descrição": "Charlie Spring e Nick Nelson não têm quase nada em comum. Charlie é um aluno dedicado e bastante inseguro por conta do bullying que sofre no colégio desde que se assumiu gay...",
        "Número de páginas": 288,
        "Url": "https://m.media-amazon.com/images/I/51wx3A+5s6L._SY445_SX342_.jpg",
        "Valor": 35.00
    },
    "Livro 39": {
        "Título": "Todas as suas (im)perfeições",
        "Autor": "Colleen Hoover",
        "Ano de publicação": 2019,
        "Descrição": "Todas as suas imperfeições narra a história de Quinn e Graham. Eles se conhecem no pior dia de suas vidas...",
        "Número de páginas": 304,
        "Url": "https://m.media-amazon.com/images/I/51is1KDs5zL._SY445_SX342_.jpg",
        "Valor": 30.00
    },
    "Livro 40": {
        "Título": "As vantagens de ser invisível",
        "Autor": "Stephen Chbosky",
        "Ano de publicação": 2007,
        "Descrição": "Coleção Azul Radical. Aventuras, desventuras e adrenalina no cotidiano dos meninos. Livro de estreia do roteirista norte-americano Stephen Chbosky...",
        "Número de páginas": 224,
        "Url": "https://m.media-amazon.com/images/I/51k0X0RixSL._SY445_SX342_.jpg",
        "Valor": 15.00
    },
    "Livro 41": {
        "Título": "Para Aqueles Que Querem Voar",
        "Autor": "Pirkko Vainio",
        "Ano de publicação": 2018,
        "Descrição": "PARA AQUELES QUE QUEREM VOAR é um livro que nos apresenta as relações entre as pessoas e as diferenças de autoconhecimento.",
        "Número de páginas": 50,
        "Url": "https://image.isu.pub/180830151613-1452488c4d318002d650ca54f71e4a58/jpg/page_1.jpg",
        "Valor": 20.00
    }
}

**Comment by adelsonsljunior** [comment]
Tá descende
